# Generated by Django 3.0.5 on 2020-04-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author_id',
            new_name='author',
        ),
    ]
